[workspace]
resolver = "2"

members = ["day*"]

[workspace.dependencies]
divan = "0.1.4"
dhat = "0.3.2"
itertools = "0.12.0"
nom = "7.1.3"
rstest = "0.18.2"

[profile.dhat]
inherits = "release"
debug = 1